"""empty message

Revision ID: 66972958ac91
Revises: 40e9aede033c
Create Date: 2018-04-20 17:39:41.067134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66972958ac91'
down_revision = '40e9aede033c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('touxiang', sa.LargeBinary(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'touxiang')
    # ### end Alembic commands ###
